# Generated by Django 4.1.5 on 2023-01-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="名称")),
                ("comment", models.CharField(max_length=256, verbose_name="描述")),
            ],
            options={
                "verbose_name": "书籍",
                "verbose_name_plural": "书籍",
            },
        ),
    ]
